seeds:
  posts:
    - handle: chillin
      postId: 4923399
    - handle: GoopySpaceShark
      postId: 7723199
    - handle: FaeAlchemist
      postId: 5824250
ratelimits:
  posts: 1
  projects: 1
  tags: 1
concurrency:
  posts: 64
  projects: 64
  tags: 64
